### ISSUE TITLE
Root npm test collects leftover .lakatos/pabst-e2e scratch tests from an interrupted run

### ISSUE THREAD

**Issue by jessealama** [jessealama/lakatos#397]
vitest.config.ts includes .lakatos/**/*.test.ts so refute's spawned vitest inherits the config. The pabst e2e suite (engines/pabst/tests/e2e.test.ts) cleans its genDir in beforeAll/afterAll, but vitest globs test files before any suite runs, so files left by an interrupted or killed run are collected: seen 2026-09-12 in the tarski-m0 worktree as 18 extra files (fail fixtures raise PABST_ISSUE, pass fixtures vanish mid-run with 'Cannot find module'). A clean rerun passes. Fix idea: remove .lakatos/pabst-e2e in tests/global-setup.ts (only when cwd is the repo root), or narrow the include. Pre-existing on main; not caused by PR #372.
